engine=DeepSpeed
option.batch_size=4
#option.s3url=s3://sagemaker-us-west-2-726335585155/sagemaker-checkpoint-test/checkpoints-klook-0529-v2-10
option.model_id = s3://sagemaker-us-west-2-726335585155/klook-model/model_first/

                